# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 17:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created', models.DateField(blank=True, null=True, verbose_name='created')),
                ('start_date', models.DateField(verbose_name='start')),
                ('end_date', models.DateField(verbose_name='end')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('added', models.DateField(default=datetime.datetime(2017, 12, 16, 17, 29, 15, 660600, tzinfo=utc), verbose_name='added')),
                ('quantity', models.IntegerField(default=1)),
                ('income_statement_10k', models.CharField(blank=True, max_length=10000, null=True)),
                ('income_statement_10q', models.CharField(blank=True, max_length=10000, null=True)),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folios2.Portfolio')),
            ],
        ),
    ]
