# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('folios2', '0002_auto_20171216_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='added',
            field=models.DateField(default=datetime.datetime(2017, 12, 17, 1, 5, 29, 660462, tzinfo=utc), verbose_name='added'),
        ),
    ]
