# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('folios2', '0004_auto_20171217_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='added',
            field=models.DateField(default=datetime.datetime(2017, 12, 17, 15, 37, 7, 668175, tzinfo=utc), verbose_name='added'),
        ),
    ]
