# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('folios2', '0005_auto_20171217_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='added',
            field=models.DateField(default=datetime.datetime(2017, 12, 17, 18, 42, 59, 959973, tzinfo=utc), verbose_name='added'),
        ),
    ]
