# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('folios2', '0007_auto_20171217_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='added',
            field=models.DateField(default=datetime.datetime(2017, 12, 17, 19, 31, 15, 769654, tzinfo=utc), verbose_name='added'),
        ),
    ]
