# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-04 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('folios2', '0008_auto_20171217_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='form_links',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='added',
            field=models.DateField(default=datetime.datetime(2018, 2, 4, 21, 3, 57, 11101, tzinfo=utc), verbose_name='added'),
        ),
    ]
